apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      {{- include "app.label" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "app.label" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.servicePort }}
          env:
            {{- if .Values.env.normal -}}
            {{- range .Values.env.normal }}
              - name: {{ .name }}
                value: {{ .value | quote }}
            {{- end -}}
            {{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret }}