apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.name }}
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Premium_LRS
  cachingMode: ReadWrite
volumeBindingMode: WaitForFirstConsumer